# serverless.yml

service: my-express-application

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      # - http: 
      #     path: /
      #     method: GET
      #     request: 
      #       parameters: 
      #         querystrings: 
      #           name: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript